KNN is used for classification purposes
The data is irregular.
Pandas reads the first line of the dataset as the variables

Given a data point, the algorithm attempts to classify the data point with one of the classes it knows

In [1]:
import sklearn
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
from sklearn import linear_model, preprocessing


In [2]:
CarData=pd.read_csv("car.data")
CarData

buying  maint   door persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

Preprocessing is used to convert non numerical data into numerical data

In [3]:
le=preprocessing.LabelEncoder()
buying=le.fit_transform(list(CarData["buying"]))
maint=le.fit_transform(list(CarData["maint"]))
door=le.fit_transform(list(CarData["door"]))
persons=le.fit_transform(list(CarData["persons"]))
lug_boot=le.fit_transform(list(CarData["lug_boot"]))
safety=le.fit_transform(list(CarData["safety"]))
cls=le.fit_transform(list(CarData["class"]))


In [4]:
buying

    

array([3, 3, 3, ..., 1, 1, 1], dtype=int64)

In [5]:
safety

array([1, 2, 0, ..., 1, 2, 0], dtype=int64)

In [6]:
cls

array([2, 2, 2, ..., 2, 1, 3], dtype=int64)

x is going to be the features and y the label i.e what we are predicting

zip makes a tuple object of all the values of the variables

In [7]:
predict="class"

In [8]:
X=list(zip(buying,maint,door,persons,lug_boot,safety))
y=list(cls)

In [9]:
x_train,x_test,y_train,y_test=sklearn.model_selection.train_test_split(X,y,test_size=0.1)

In [10]:
x_train, y_train

([(3, 0, 1, 1, 1, 0),
  (3, 3, 3, 0, 0, 2),
  (3, 0, 2, 0, 0, 2),
  (3, 0, 3, 1, 0, 2),
  (2, 2, 1, 2, 1, 1),
  (1, 1, 2, 0, 0, 2),
  (1, 3, 2, 0, 1, 2),
  (1, 3, 2, 0, 0, 2),
  (2, 3, 3, 1, 0, 1),
  (2, 2, 3, 0, 2, 1),
  (2, 3, 1, 1, 2, 2),
  (3, 0, 1, 2, 2, 1),
  (0, 0, 3, 1, 0, 0),
  (0, 1, 0, 2, 1, 2),
  (3, 3, 2, 1, 1, 2),
  (1, 0, 3, 1, 2, 2),
  (3, 3, 1, 1, 2, 0),
  (1, 0, 3, 0, 1, 0),
  (2, 0, 0, 1, 0, 0),
  (0, 1, 0, 1, 0, 1),
  (1, 1, 0, 0, 0, 1),
  (1, 1, 2, 2, 2, 2),
  (2, 3, 3, 0, 1, 2),
  (3, 1, 0, 1, 0, 2),
  (3, 1, 2, 1, 0, 0),
  (3, 0, 3, 0, 1, 2),
  (1, 2, 2, 2, 0, 1),
  (0, 2, 1, 0, 0, 2),
  (3, 0, 2, 2, 0, 1),
  (0, 1, 0, 2, 1, 1),
  (1, 0, 2, 1, 0, 0),
  (2, 1, 1, 1, 0, 2),
  (2, 0, 0, 1, 2, 0),
  (3, 2, 1, 2, 0, 2),
  (1, 2, 0, 0, 1, 0),
  (2, 0, 3, 1, 2, 0),
  (2, 1, 3, 0, 0, 1),
  (2, 0, 3, 2, 0, 0),
  (3, 3, 1, 1, 2, 2),
  (3, 1, 2, 1, 0, 2),
  (0, 3, 2, 1, 2, 1),
  (2, 3, 0, 1, 0, 1),
  (1, 1, 1, 0, 1, 2),
  (0, 3, 2, 0, 1, 0),
  (0, 1, 3, 1, 1, 0),
  (0, 1, 1

In [13]:
model=KNeighborsClassifier(n_neighbors=9)
model.fit(x_train,y_train)
acc=model.score(x_test,y_test)
acc

0.9479768786127167

Now to see what the data points are and what the prediction is.

In [15]:
predicted=model.predict(x_test)
names=['unacc','acc','good','vgood']

for x in range(len(predicted)):
    print("Predicted: ",names[predicted[x]], "Data: ", x_test[x], "Actual: ", names[y_test[x]])
    #To show the distance between the data points
    n=model.kneighbors([x_test[x]],9,True)
    print("N;", n)

Predicted:  unacc Data:  (1, 1, 1, 1, 2, 2) Actual:  unacc
N; (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.41421356]]), array([[ 148,  809,  504,  890,  899,  230, 1139,  300,  967]],
      dtype=int64))
Predicted:  good Data:  (2, 3, 2, 0, 0, 0) Actual:  good
N; (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.41421356]]), array([[1046, 1373, 1441,  557,  389,  405, 1278,  114,  585]],
      dtype=int64))
Predicted:  acc Data:  (1, 2, 2, 2, 1, 2) Actual:  acc
N; (array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]]), array([[  59,  413, 1195, 1240,   63,  176,  679,  295, 1513]],
      dtype=int64))
Predicted:  good Data:  (3, 3, 2, 0, 2, 0) Actual:  good
N; (array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.41421356, 1.41421356, 1.41421356]]), array([[1435,  513,  806,  655, 1391,  858,  954,  681, 1286]],
      dtype=

KNN measures distance between the data point to be classified and the rest of the data and gets the k number of neighbors that are closest to it. And by which class has the highest number of neighbors, it adds that data point to that class.